version: "3.7"

services:
  xenial-hdr-merge:
    user: ${UID?UID must be set}:${GID?GID must be set}
    build:
      context: .
      args:
        uid: $UID
        workspace: /var/tmp/workspace
    environment:
      - VNC_PASSWORD=${VNC_PASSWORD:-secret}
    ports:
      - 5900:5900
    volumes:
      - .:/var/tmp/workspace
